#!/usr/bin/env python3
"""
copy_fonts.py - Safely export and copy selected font files, licenses, and implementation snippets.

Copies chosen font families (.woff2, .ttf, .otf, variable) to target project asset folders,
optionally packages associated license text, and emits copy-pasteable CSS @font-face or Flutter/React Native code.
"""

import os
import sys
import json
import shutil
import argparse
from typing import Dict, List, Any, Optional

sys.stdout.reconfigure(encoding='utf-8')

ROOT_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
if not os.path.exists(os.path.join(ROOT_DIR, "catalog")):
    ROOT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

CATALOG_PATH = os.path.join(ROOT_DIR, "catalog", "fonts.json")


def load_catalog(cat_path: str) -> Dict[str, Dict[str, Any]]:
    with open(cat_path, "r", encoding="utf-8") as f:
        data = json.load(f)
    fonts_by_id = {}
    for f in data.get("fonts", []):
        fonts_by_id[f["id"]] = f
        fonts_by_id[f["name"].lower()] = f
    return fonts_by_id


def generate_css_font_face(copied_files: List[Dict[str, Any]], dest_rel_to_css: str = "../fonts") -> str:
    """Generate CSS @font-face declarations for copied files."""
    lines = ["/* =========================================================================="]
    lines.append("   Generated by Font Intelligence Engine: @font-face declarations")
    lines.append("   ========================================================================== */\n")

    # Group by family name
    by_fam = {}
    for item in copied_files:
        if item.get("is_license"):
            continue
        fam = item["family_name"]
        by_fam.setdefault(fam, []).append(item)

    for fam, files in sorted(by_fam.items()):
        # Separate variable vs static
        var_files = [f for f in files if f.get("variable")]
        static_files = [f for f in files if not f.get("variable")]

        if var_files:
            for vf in var_files:
                fmt = vf["format"]
                fmt_str = "woff2-variations" if fmt == "woff2" else "truetype-variations"
                lines.append(f"@font-face {{")
                lines.append(f"  font-family: '{fam}';")
                lines.append(f"  src: url('{dest_rel_to_css}/{vf['filename']}') format('{fmt_str}');")
                lines.append(f"  font-weight: 100 900;")
                lines.append(f"  font-style: {'italic' if vf.get('style') == 'italic' else 'normal'};")
                lines.append(f"  font-display: swap;")
                lines.append(f"}}\n")
        else:
            for sf in static_files:
                fmt = sf["format"]
                fmt_map = {"woff2": "woff2", "woff": "woff", "ttf": "truetype", "otf": "opentype"}
                fmt_str = fmt_map.get(fmt, fmt)
                lines.append(f"@font-face {{")
                lines.append(f"  font-family: '{fam}';")
                lines.append(f"  src: url('{dest_rel_to_css}/{sf['filename']}') format('{fmt_str}');")
                lines.append(f"  font-weight: {sf.get('weight', 400)};")
                lines.append(f"  font-style: {sf.get('style', 'normal')};")
                lines.append(f"  font-display: swap;")
                lines.append(f"}}\n")

    return "\n".join(lines)


def generate_flutter_yaml(copied_files: List[Dict[str, Any]], asset_prefix: str = "assets/fonts") -> str:
    """Generate Flutter pubspec.yaml font section."""
    lines = ["# Flutter pubspec.yaml font definitions"]
    lines.append("flutter:")
    lines.append("  fonts:")

    by_fam = {}
    for item in copied_files:
        if item.get("is_license"):
            continue
        fam = item["family_name"]
        by_fam.setdefault(fam, []).append(item)

    for fam, files in sorted(by_fam.items()):
        lines.append(f"    - family: {fam}")
        lines.append(f"      fonts:")
        for f in files:
            weight = f.get("weight", 400)
            style_str = "        style: italic\n" if f.get("style") == "italic" else ""
            lines.append(f"        - asset: {asset_prefix}/{f['filename']}")
            lines.append(f"          weight: {weight}")
            if style_str:
                lines.append(style_str.rstrip())

    return "\n".join(lines)


def copy_font_assets(
    fonts_dict: Dict[str, Dict[str, Any]],
    font_identifiers: List[str],
    destination_dir: str,
    target_formats: List[str],
    include_license: bool = True,
    dry_run: bool = False,
    force_export: bool = False
) -> List[Dict[str, Any]]:
    """Copy font files to destination."""
    dest_path = os.path.abspath(destination_dir)
    copied_items = []

    for fid in font_identifiers:
        key = fid.strip().lower()
        font_entry = fonts_dict.get(key)
        if not font_entry:
            print(f"Warning: Font '{fid}' not found in catalog. Skipping.", file=sys.stderr)
            continue

        family_name = font_entry["name"]
        dist_status = font_entry.get("distribution_status", "unknown")
        lic_type = font_entry.get("license", {}).get("type", "Unknown")

        # Distribution Status Export Gate
        if dist_status == "restricted" and not force_export:
            print(f"[EXPORT BLOCKED] Font '{family_name}' ({fid}) is RESTRICTED (demo cut or non-commercial EULA).", file=sys.stderr)
            print(f"                 Binary export prohibited for public distribution. Pass --force-export to override for private testing.", file=sys.stderr)
            continue
        elif dist_status == "unknown" and not force_export:
            print(f"[EXPORT BLOCKED] Font '{family_name}' ({fid}) has UNKNOWN licensing provenance. Export blocked.", file=sys.stderr)
            print(f"                 Pass --force-export to override for private testing.", file=sys.stderr)
            continue
        elif dist_status == "catalog-only":
            print(f"[LICENSE NOTICE] Font '{family_name}' ({fid}) is CATALOG-ONLY ({lic_type}).", file=sys.stderr)
            print(f"                 Permitted for local design recommendations; raw file redistribution requires foundry grant or commercial license proof.", file=sys.stderr)
        elif dist_status == "public-asset":
            print(f"[APPROVED] Font '{family_name}' ({fid}) verified for public distribution ({lic_type}).")

        files = font_entry.get("files", [])

        # Filter by format
        matching_files = [f for f in files if f.get("format", "").lower() in target_formats]
        # If no exact match (e.g. woff2 requested but only ttf exists), fallback to available
        if not matching_files and files:
            matching_files = files

        for f_info in matching_files:
            rel_path = f_info["path"]
            src_abs = os.path.join(ROOT_DIR, rel_path)
            if not os.path.exists(src_abs):
                print(f"Warning: File not found on disk: {src_abs}", file=sys.stderr)
                continue

            fname = os.path.basename(src_abs)
            dest_file = os.path.join(dest_path, fname)

            record = {
                "font_id": font_entry["id"],
                "family_name": family_name,
                "source": src_abs,
                "destination": dest_file,
                "filename": fname,
                "format": f_info.get("format"),
                "weight": f_info.get("weight", 400),
                "style": f_info.get("style", "normal"),
                "variable": f_info.get("variable", False),
                "size_bytes": os.path.getsize(src_abs)
            }
            copied_items.append(record)

            if not dry_run:
                os.makedirs(dest_path, exist_ok=True)
                shutil.copy2(src_abs, dest_file)

        # Include license
        if include_license:
            lic = font_entry.get("license", {})
            ref_files = lic.get("reference_files", [])
            for rf in ref_files:
                lic_abs = os.path.join(ROOT_DIR, rf)
                if os.path.exists(lic_abs) and os.path.isfile(lic_abs):
                    lic_name = f"{font_entry['id']}-LICENSE{os.path.splitext(rf)[1]}"
                    lic_dest = os.path.join(dest_path, lic_name)
                    copied_items.append({
                        "font_id": font_entry["id"],
                        "family_name": family_name,
                        "source": lic_abs,
                        "destination": lic_dest,
                        "filename": lic_name,
                        "is_license": True,
                        "size_bytes": os.path.getsize(lic_abs)
                    })
                    if not dry_run:
                        os.makedirs(dest_path, exist_ok=True)
                        shutil.copy2(lic_abs, lic_dest)
                    break

    return copied_items


def main():
    parser = argparse.ArgumentParser(
        description="Safely copy selected font binaries, licenses, and generate implementation snippets."
    )
    parser.add_argument("--fonts", "-f", required=True, help="Comma-separated font IDs or names (e.g. 'chillax,general-sans')")
    parser.add_argument("--dest", "-d", default="dist/fonts", help="Target destination directory (default: 'dist/fonts')")
    parser.add_argument("--formats", default="woff2,ttf", help="Comma-separated formats to copy (default: 'woff2,ttf')")
    parser.add_argument("--include-license", action="store_true", default=True, help="Copy license files alongside fonts (default: true)")
    parser.add_argument("--no-license", dest="include_license", action="store_false", help="Do not copy license files")
    parser.add_argument("--snippets", choices=["css", "flutter", "all", "none"], default="css", help="Implementation snippets to generate (default: css)")
    parser.add_argument("--dry-run", action="store_true", help="Preview operations without copying files")
    parser.add_argument("--force-export", action="store_true", help="Force export of restricted or unknown fonts for private testing")
    parser.add_argument("--catalog", default=CATALOG_PATH, help="Path to fonts.json")

    args = parser.parse_args()

    if not os.path.exists(args.catalog):
        print(f"Error: Catalog file '{args.catalog}' not found.", file=sys.stderr)
        sys.exit(1)

    fonts_dict = load_catalog(args.catalog)
    target_ids = [fid.strip() for fid in args.fonts.split(",") if fid.strip()]
    target_formats = [fmt.strip().lower() for fmt in args.formats.split(",") if fmt.strip()]

    copied = copy_font_assets(
        fonts_dict=fonts_dict,
        font_identifiers=target_ids,
        destination_dir=args.dest,
        target_formats=target_formats,
        include_license=args.include_license,
        dry_run=args.dry_run,
        force_export=args.force_export
    )

    print("=" * 80)
    print("FONT ASSET EXPORT REPORT")
    print("=" * 80)
    print(f"• Target Fonts:     {', '.join(target_ids)}")
    print(f"• Destination:      {os.path.abspath(args.dest)}")
    print(f"• Formats Filter:   {', '.join(target_formats)}")
    print(f"• Dry Run:          {'YES (Preview only)' if args.dry_run else 'NO (Files copied)'}")
    print(f"• Total Files:      {len(copied)} files ({sum(c.get('size_bytes', 0) for c in copied) / 1024:.1f} KB)")
    
    # Audit licensing and redistribution compliance
    lic_warnings = []
    for fid in target_ids:
        fe = fonts_dict.get(fid.strip().lower())
        if fe:
            lic = fe.get("license", {})
            tracking = lic.get("tracking", {})
            st = (tracking.get("verification_status") or lic.get("risk_level", "unknown")).lower()
            redist = tracking.get("redistribution", lic.get("redistribution_allowed", False))
            commercial = tracking.get("commercial_use", lic.get("commercial_use", False))
            if st in ["restricted", "proof-needed", "unknown"] or not redist:
                lic_warnings.append(
                    f"  [!] '{fe['name']}': Status='{st.upper()}', Commercial={commercial}, Redistribution={redist}.\n"
                    f"      Warning: This font carries licensing constraints. Redistribution on public repositories (GitHub) or production deployment requires verified proof or license purchase. See docs/redistribution-review.md."
                )
    if lic_warnings:
        print("-" * 80)
        print("LEGAL & REDISTRIBUTION AUDIT WARNINGS:")
        for lw in lic_warnings:
            print(lw)

    print("-" * 80)
    for c in copied:
        tag = "[LICENSE]" if c.get("is_license") else f"[{c.get('format', '').upper()}]"
        print(f"  • {tag:<10} {c['filename']} ({c.get('size_bytes', 0) / 1024:.1f} KB) -> {os.path.basename(args.dest)}/{c['filename']}")
    print("-" * 80)

    if args.snippets in ["css", "all"]:
        css_snippet = generate_css_font_face(copied)
        print("\n--- GENERATED CSS @font-face ---")
        print(css_snippet)

    if args.snippets in ["flutter", "all"]:
        flutter_snippet = generate_flutter_yaml(copied)
        print("\n--- GENERATED FLUTTER pubspec.yaml ---")
        print(flutter_snippet)

    print("=" * 80)


if __name__ == "__main__":
    main()
